* Software Requirements
1. The game lets players save and load their game from any point outside of a
   battle or cutscene.
2. The game has AI that will fight the player in single player.
3. The game supports local multiplayer where two players play on the same
   computer. (mostly for debugging and because AI is hard)
* Core Game
** Objectives
Much like the game FTL, your vessel is caught in enemy territory, and your
carrier with all onboard fighters needs to attempt to return to safe territory.

This is done by jumping from system to system, facing off against various
enemies at nearly every turn, stopping at shops to refuel and rearm.
*** Finale
Once the player reaches friendly territory, the game will be put on hold until
two other games are finished. At this point, all three forces will be joined
into one large battle where they must repel a small armada of enemy ships that
followed them home.
** Battles
All battles will take place in space fighters in an SRPG format.
*** Types of Objectives
- destroying all enemy fighters,
- destroying a particular “boss” enemy
- defending the carrier for some number of turns
*** Map Types
Most maps will be simply empty space with two opposing forces of fighters and
carriers, normally with a background of whatever interstellar object is being
orbited. Sometimes, there will be atmospheric battles where the fighters have to
fight around buildings or something, and stationary ground turrets might attack
them.
*** Unit’s
Each Unit has multiple components, each with some maximum and current energy
amounts. As the components are damaged, the component’s maximum energy is
decreased until it is completely disabled. Some Unit’s are energizing ships
which can raise the maximum energy of the components again.

Unit’s also have a total energy capacity that is damaged whenever a component is
forced to lose energy due to damage. For example, let the shield component have
a maximum energy of 5 and a currently allocated energy of 4. If the shield takes
3 points of damage, both its maximum and current energy will then be 2, and 2
points of energy will be lost from the total energy capacity. Once the total
energy capacity drops to 0, the unit is disabled for the remainder of the
battle.
**** Components
- shields: reduces damage taken and evasion chance as energy increases; with no
  energy, there is no damage reduction
- engines: increases movement range as energy increases; with no energy, the
  fighter can no longer move
- weapons: increases attack damage as energy increases; with no energy, the
  fighter can no longer attack
**** Movement
Since these are fighters, there aren’t any differing movement costs for
different tiles. Unit’s can move through allied Unit’s but are blocked by
enemies. Additionally, there are other tiles that may be impassable. Unit’s may 
not end their turn on top of another Unit, even an ally.
*** Turret’s
There are two different situations in which Turret’s are in battle: in a carrier
battle where the Turret’s are part of the carriers themselves and in atmospheric
battles where there may be ground-based Turret’s.

Turret’s do /not/ have any kind of energy allocation and instead they simply 
have a total energy value that can be damaged by enemy attacks. They cannot move
at all, but they have an unlimited attack range. The tradeoff is that when 
attacking fighters there is a very high chance they will evade the attack with
their shields, but if their shields are disabled…

Turret’s have a very high attack power against fighters, but not against other
Turret’s. Fighters do not have this hindrance, and thus make for very good
Turret destroyers…if they can get close enough.

Turret’s cannot be energized by repair ships in battle, and as such any damage 
damage dealt to them is permanent.
*** Attacking
Each Unit has some attack range determined by their inventory. This will usually
be around a two tile range. Some weapons will have an AOE (namely torpedoes)
that will also damage other Enemy units within some radius of the affected 
target, but only if the initial target is hit.
** Exploration
In between battles, there is an FTL-style jump map.
*** Fuel
Each jump takes some amount of fuel from the carrier, as does launching
fighters. Each fighter takes some amount of fuel to launch, so launching as few
as possible may be advantageous for cost-concerned players. Fuel can be bought
at shops for some amount of scrap.
*** Scrap
The main currency in the game, scrap can be gathered from vanquished foes and
from selling items in shops. It can be used to buy items or fuel from shops.
*** Items
Each fighter will have one unique, built-in item that cannot be removed. These
define a fighter’s “class.” Other items can be freely moved from fighter to
fighter, with probably around 2-5 item slots per fighter.

Items will have different abilities, most of which will be more than simple stat
boosts. Current ideas (pre-balance checks) are as follows:
- projectile attractor :: all attacks against neighboring enemies are redirected
     toward this unit
- energy concentrator :: all attacks by this unit are strengthened by the number
     of nearby allies
- enemy repulsor :: enemies cannot travel within some range of this unit
- damage diffusor :: a portion of any damage taken by this unit is shared among
     nearby units
- reenergizer :: can “heal” allied units, restoring some of their lost energy
     capacity
* The Board
** Tile Members
- public:
  + neighbors: Tile[4]
  + accessible: bool
  + x position: double
  + y position: double
- private:
  + occupying unit: Unit
  + transient unit: Unit
  + image: SDL2image
** Basics
Each Unit will also have a pointer to the Tile it is a member of. The Map has an
array of all the Tiles, with extra, impassable Tiles around the edge to both
serve as border and to draw.
** TODO Creation and Deletion
file loading? saving? what?
** Movement
For a Unit to move around the map, it first gets access to the Tile it is
currently occupying. Then, once a direction is supplied, that Tile calls its
neighbor’s move function. The method first checks if the move is legal,
specifically by checking the accessibility flag. If it is legal, the method
begins a new thread that will move the Unit from one Tile to the next. During
this transition time, the Unit is in the destination Tile and is drawn with an
extra displacement.

For determining move range, the starting Tile is found, then a recursive process
begins to find all accessible Tile’s. Each Tile has its accessibility flag set
to false, and the recursive function just sets that flag to true. The path to
get to the destination Tile is never used, calculated, or recorded.
** Drawing
Each Tile has a draw procedure that will both draw its background and any Unit’s
currently in the tile. If the transient Unit is currently moving into the Tile,
it will be drawn with some displacement from the base Tile.
* Units
** Unit Members
- public:
  + name: string
  + current tile: Tile
- private:
  + hull health: int
  + shield health: int
  + engine health: int
  + weapon health: int
  + total power: int
  + shield power: int
  + engine power: int
  + weapon power: int
** Unit Subclasses
- Enemy
- Ally
- Carrier Part
* Loading Files
Note that this may change later for more optimized saving…but honestly these
files will be tiny for the most part anyways, so I’m not sure it’s worth the
trouble.

Additionally, formats /will/ be changing a lot as more data needs to be stored
if new things are needed to be added. Don’t expect old saves to work for long.
** Battles
*** Textures
First is a list of all the textures that will be loaded for the map. This simply
contains a number of textures to load and then a list of file paths on separate
lines.

Example:
3
~/img/test.png
~/img/other.png
~/img/final.png
*** Tiles
To define the layout, there are two numbers separated by a space determining the
dimensions of the entire map. Next is a list of all the information needed for
each Tile. This is ordered as:
- index of referenced Texture (using the above example, test.png is 0, other.png
  is 1…)
- 4 numbers indicating, in order, the x, y, w, and h of the source rectangle or
  0 0 0 0 if the source rectangle should include the whole texture
- a 1 or 0 indicating that the Tile is accessible or inaccessible, respectively

These Tiles are ordered from top to bottom, left to right, just like reading
standard English.

Example:
2 2
0 0 0 0 0 1
0 0 0 0 0 0
1 50 0 50 50 1
1 50 50 50 50 1

This translates to:
| test (open)  | test (blocked) |
|--------------+----------------|
| other (open) | other(open)    |
*** Units
The list of Units starts with the number of Units on the board. Next is a
Texture index and source rectangle dimensions just like the Tiles. Additionally
there is a Tile index at the very end. Since the location of the Unit is
dependent on the Tile it points at, the order of the lines doesn’t matter.

Example:
2
2 0 0 50 50 0
2 0 50 50 50 2
*** Complete Example
3
~/img/test.png
~/img/other.png
~/img/final.png
2 2
0 0 0 0 0 1
0 0 0 0 0 0
1 50 0 50 50 1
1 50 50 50 50 1
2
2 0 0 50 50 0
2 0 50 50 50 2
